import { TimelineEvent } from './event'

export const EVENTS_LIST: TimelineEvent[] = [
    {title: "Write Angle Stall", description: "The first ever!", date: new Date("2017-09-08"), path: "assets/wastall.jpg", type: "image"},
    {title: "BITS Hyderabad", description: "Varsha's most unexpectedly-fun birthday week", date: new Date("2018-01-19"), path: "assets/hydgirls.jpg", type: "image"},
    {title: "Aatmatrisha '18", description: "To-be Mana's cover picture", date: new Date("2018-03-07"), path: "assets/firstat.JPG", type: "image"},
    {title: "Sleepover #1", description: "Shaantam-papam at Vaani's house", date: new Date("2018-05-23"), path: "assets/vaanihouse.jpg", type: "image"},
    {title: "Regular Class Pt. 1", description: "Mana eats bowtie pasta", date: new Date("2018-10-15"), path: "assets/pasta.jpg", type: "image"},
    {title: "Varsha Birthday '19", description: "Varsha wants to look pretty", date: new Date("2019-01-19"), path: "assets/vbdpicture.jpg", type: "image"},
    {title: "Sleepover #2", description: "Newly Cult-ed Varsha and Cult Pro Mana", date: new Date("2019-02-02"), path: "assets/aftercult.jpg", type: "image"},
    {title: "The Asian Curry House", description: "Fancy in Aisha's clothes", date: new Date("2019-02-02"), path: "assets/tach.jpg", type: "image"},
    {title: "Japan Habba", description: "Goal-Setting: Japan tour in the Eighth Semester", date: new Date("2019-02-03"), path: "assets/japanhabba.jpg", type: "image"},
    {title: "Red Yellow '19", description: "And a perfectly coloured duster", date: new Date("2019-03-05"), path: "assets/redyellow.jpeg", type: "image"},
    {title: "Formals '19", description: "Varsha is funny and cool", date: new Date("2019-03-06"), path: "assets/formals.jpg", type: "image"},
    {title: "Ethnic '19", description: "Varsha's Favourite Picture with Mana", date: new Date("2019-03-08"), path: "assets/ethnic.jpg", type: "image"},
    {title: "Chianti", description: "Pretty girls in a could-be Colgate ad", date: new Date("2019-03-21"), path: "assets/chianti.jpg", type: "image"},
    {title: "May the Fourth", description: "Varsha talks about furniture a lot, and Malazan, before finally getting to the senti", date: new Date("2019-05-04"), path: "assets/may42019.jpg", type: "image"},
    {title: "First Day at Work", description: "Mana makes Varsha glitter, or sparkle, or magic, or stardust", date: new Date("2019-05-27"), path: "assets/firstdaywork.jpg", type: "image"},
    {title: "Bellandur Interns' Outing", description: "Varsha's New Old Sandals", date: new Date("2019-06-02"), path: "assets/sandals.jpeg", type: "image"},
    {title: "Smol Mana", description: "Mana remembers smol Mana", date: new Date("2019-07-28"), path: "assets/smolMana.jpg", type: "image"},
    {title: "Mana's Cactii", description: "A new cherry is born!", date: new Date("2019-08-07"), path: "assets/cherry.jpg", type: "image"},
    {title: "Regular Class Pt. 2", description: "Mana and Varsha take a sneaky picture", date: new Date("2019-08-27"), path: "assets/class2.jpeg", type: "image"},
    {title: "Ante DP Test", description: "Varsha diligently copies diligently taken notes", date: new Date("2019-09-17"), path: "assets/dpnotes.jpeg", type: "image"},
    {title: "Mana ft. Shriyu", description: "Mana seems like a very happy stalker; it's also Shriya's 19 1/3rd birthday", date: new Date("2019-09-19"), path: "assets/stalker.jpg", type: "image"},
    {title: "Varsha's Tinder Sojourn", description: "Varsha is not even wearing her own clothes; that's how much of a player she is", date: new Date("2019-09-22"), path: "assets/tinder.jpg", type: "image"},
    {title: "Turtle #1", description: "Mana goes to Hampi, acquires a turtle and does not meet Suraj", date: new Date("2019-09-27"), path: "assets/turtle1.jpg", type: "image"},
    {title: "Drenched in Rain", description: "Varsha remembers rain stories", date: new Date("2019-09-27"), path: "assets/rain.jpg", type: "image"},
    {title: "Kalpana aka WT-II project", description: "Mana, Vaani and Varsha spend 24 hours too many at PESIT South", date: new Date("2019-10-04"), path: "assets/kalpana3.jpg", type: "image"},
    {title: "Westside Accessories", description: "Varsha meets her new favourite accessories", date: new Date("2019-10-06"), path: "assets/westside.jpeg", type: "image"},
    {title: "Golu at Varsha's House", description: "Ft. how we all hate North Indians and aforementioned accessories", date: new Date("2019-10-08"), path: "assets/golu.jpg", type: "image"},
    {title: "Mana's Fin-jury", description: "Mana gets her finger taped; also Varsha takes the Blossom Pinto call", date: new Date("2019-10-10"), path: "assets/finjury.jpg", type: "image"},
    {title: "Exploring the World Pt. 1", description: "Mana's #TB to 2007, on Children's Day", date: new Date("2019-10-14"), path: "assets/expl1.jpg", type: "image"},
    {title: "Write Angle Badges!", description: "Mana finally visits Modern Printing, Ulsoor!", date: new Date("2019-10-24"), path: "assets/badges.jpg", type: "image"},
    {title: "The Best Friend Day", description: "Very happy sad sad happy", date: new Date("2019-10-25"), path: "assets/crycry.jpg", type: "image"},
    {title: "Open Mic '19", description: "Some traditions are worth remembering: fairy lights and soft music and loving art", date: new Date("2019-10-25"), path: "assets/openmicdraw.png", type: "image"},
    {title: "The A Team", description: "Smiling because it happened", date: new Date("2019-10-25"), path: "assets/lastopenmic.jpg", type: "image"},
    {title: "Mana's Interview (1)", description: "Mana wants to be called Daddy and also takes an office interview, hmm", date: new Date("2019-10-29"), path: "assets/manainterview.jpg", type: "image"},
    {title: "Polaroid", description: "Varsha uses an instant camera for the first time!", date: new Date("2019-11-25"), path: "assets/polaroid.jpg", type: "image"},
    {title: "Mysore Diaries: Stone Temple", description: "The wind is as happy as the girls", date: new Date("2019-11-29"), path: "assets/wind.jpg", type: "image"},
    {title: "Mysore Diaries: Ranganathittu", description: "A bird in focus is worth two in the blur", date: new Date("2019-11-29"), path: "assets/mysorebird.jpg", type: "image"},
    {title: "Mysore Diaries: Rasta Cafe", description: "Rasta pasta is expensive", date: new Date("2019-11-29"), path: "assets/rasta.jpeg", type: "image"},
    {title: "Varsha's First Karuta Card", description: "ちはやふる", date: new Date("2019-12-18"), path: "assets/karuta.jpeg", type: "image"},
    {title: "Skirt Shopping", description: "Varsha likes shopping with Dweepa and Mana!", date: new Date("2019-12-27"), path: "assets/skirt.jpg", type: "image"},
    {title: "Take your Badge to Work Day", description: "Varsha is hit with なつかしい and wants to show WA off", date: new Date("2020-01-20"), path: "assets/badgetowork.jpeg", type: "image"},
    {title: "Train Reading", description: "Mana is still in India", date: new Date("2020-01-22"), path: "assets/ikigai.jpg", type: "image"},
    {title: "Cact-with-a-Hat", description: "Every girl dreams of her wedding; Mana dreams of a house", date: new Date("2020-01-25"), path: "assets/cactushat.jpg", type: "image"},
    {title: "Singapore Shopping", description: "Mana is equipped with (T/L)BD", date: new Date("2020-01-27"), path: "assets/tbd.jpg", type: "image"},
    {title: "House-Gift Shopping for Dweeps and Malaika", description: "Mana visits the lake and AECS Layout!", date: new Date("2020-02-05"), path: "assets/aecs.jpg", type: "image"},
    {title: "Mirror Selfie", description: "Yes, Mana's still here, stop asking", date: new Date("2020-02-12"), path: "assets/mirrorselfie.png", type: "image"},
    {title: "Turtle #2", description: "Varsha's gift, like her, is smol and sassy", date: new Date("2020-02-28"), path: "assets/turtle2.jpg", type: "image"},
    {title: "Exploring the World Pt. 2", description: "No, she's in Singapore now; yes, she knows about Corona, stop talking now", date: new Date("2020-03-09"), path: "assets/coronameme.jpg", type: "image"},
    {title: "Mana tries Pottery!", description: "Dark circles and pastel colours", date: new Date("2020-03-21"), path: "assets/pottery.jpeg", type: "image"},
    {title: "Club Penguin!", description: "More なつかしい", date: new Date("2020-03-28"), path: "assets/clubpenguin.jpg", type: "image"},
    {title: "Zoom Birthday Party", description: "Of toast cake and treasure hunt and most things Mana", date: new Date("2020-05-04"), path: "assets/toastcake.png", type: "image"},
    {title: "Blockchain", description: "Of very many fun talks across very many days", date: new Date("2019-08-19"), path: "assets/blockchain.jpg", type: "image"},
    {title: "Kdramas: A Design Pattern", description: "Varsha doesn't know how to represent most of the points in UML", date: new Date("2019-11-10"), path: "assets/kdrama.jpg", type: "image"},
    {title: "Rude Awakening", description: "Mana will not let Varsha be lazy", date: new Date("2019-05-30"), path: "assets/wantsleep.jpg", type: "image"},
    {title: "Neurotic Varsha", description: "Clue: The Bell Jar", date: new Date("2019-09-05"), path: "assets/updown.jpg", type: "image"},
    {title: "Gilly's", description: "Mana and Varsha eat a lot of pesto and pizza", date: new Date("2019-05-30"), path: "assets/gillys.jpeg", type: "image"}
]
